#include<iostream>
#include<time.h>
#include<unistd.h> 
#include <windows.h>
void a(){
	system("cls");
}
void write_title(void){

	system("TITLE A ");
	a();
	system("TITLE A s");
	a();
	system("TITLE A si");
	a();
	system("TITLE A sim");
	a();
	system("TITLE A simp");
	a();
	system("TITLE A simpl");
	a();
	system("TITLE A simple");
	a();
	system("TITLE A simple o");
	a();
	system("TITLE A simple op");
	a();
	system("TITLE A simple ope");
	a();
	system("TITLE A simple open");
	a();
	system("TITLE A simple open s");
	a();
	system("TITLE A simple open so");
	a();
	system("TITLE A simple open sou");
	a();
	system("TITLE A simple open sour");
	a();
	system("TITLE A simple open sourc");
	a();
	system("TITLE A simple open source");
	a();
	system("TITLE A simple open source k");
	a();
	system("TITLE A simple open source ke");
	a();
	system("TITLE A simple open source key");
	a();
	system("TITLE A simple open source keyl");
	a();
	system("TITLE A simple open source keylo");
	a();
	system("TITLE A simple open source keylog");
	a();
	system("TITLE A simple open source keylogg");
	a();
	system("TITLE A simple open source keylogge");
	a();
	system("TITLE A simple open source keylogger");
	a();
	system("TITLE A simple open source keylogger c");
	a();
	system("TITLE A simple open source keylogger cr");
	a();
	system("TITLE A simple open source keylogger cre");
	a();
	system("TITLE A simple open source keylogger crea");
	a();
	system("TITLE A simple open source keylogger creat");
	a();
	system("TITLE A simple open source keylogger creato");
	a();
	system("TITLE A simple open source keylogger creator");
	sleep(1);                                                 //se da errore qui e hai una versione vecchia del compilatore sostituisci con: Sleep;
	a();
	system("TITLE C");
	a();
	system("TITLE Co");
	a();
	system("TITLE Cod");
	a();
	system("TITLE Code");
	a();
	system("TITLE Codec");
	a();
	system("TITLE Codec b");
	a();
	system("TITLE Codec by");
	a();
	system("TITLE Codec by A");
	a();
	system("TITLE Codec by An");
	a();
	system("TITLE Codec by Ang");
	a();
	system("TITLE Codec by Ange");
	a();
	system("TITLE Codec by Angel");
	a();
	system("TITLE Codec by Angelo");
	sleep(2);                                
	a();
	system("TITLE A simple open source keylogger creator");
}
